"""parse diagnostics

Revision ID: 58e935622266
Revises: 726e4199c344
Create Date: 2026-07-22 22:24:32.272371

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e935622266'
down_revision: str | None = '726e4199c344'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parse_diagnostics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repository_id', sa.String(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=True),
    sa.Column('relative_path', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parse_diagnostics', schema=None) as batch_op:
        batch_op.create_index('ix_parse_diagnostics_snapshot', ['snapshot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parse_diagnostics', schema=None) as batch_op:
        batch_op.drop_index('ix_parse_diagnostics_snapshot')

    op.drop_table('parse_diagnostics')
    # ### end Alembic commands ###
