"""initial schema

Revision ID: 726e4199c344
Revises: 
Create Date: 2026-07-22 21:55:28.700887

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '726e4199c344'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_records',
    sa.Column('embedding_key', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('normalization_version', sa.String(), nullable=False),
    sa.Column('namespace', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('embedding_key')
    )
    with op.batch_alter_table('embedding_records', schema=None) as batch_op:
        batch_op.create_index('ix_embedding_records_content', ['content_hash'], unique=False)

    op.create_table('repositories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('root_path', sa.String(), nullable=False),
    sa.Column('normalized_root_path', sa.String(), nullable=False),
    sa.Column('is_git_repository', sa.Boolean(), nullable=False),
    sa.Column('default_branch', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_root_path')
    )
    op.create_table('logical_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repository_id', sa.String(), nullable=False),
    sa.Column('normalized_path', sa.String(), nullable=False),
    sa.Column('qualified_name', sa.String(), nullable=True),
    sa.Column('chunk_role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logical_chunks', schema=None) as batch_op:
        batch_op.create_index('ix_logical_chunks_repo_path', ['repository_id', 'normalized_path'], unique=False)

    op.create_table('model_migrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repository_id', sa.String(), nullable=True),
    sa.Column('source_namespace', sa.String(), nullable=False),
    sa.Column('target_namespace', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('active_chunk_count', sa.Integer(), nullable=False),
    sa.Column('embedded_chunk_count', sa.Integer(), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('evaluation_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repository_id', sa.String(), nullable=False),
    sa.Column('snapshot_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('deterministic_index_status', sa.String(), nullable=False),
    sa.Column('semantic_index_status', sa.String(), nullable=False),
    sa.Column('semantic_coverage', sa.Float(), nullable=False),
    sa.Column('pending_embedding_count', sa.Integer(), nullable=False),
    sa.Column('active_embedding_namespace', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('commit_sha', sa.String(), nullable=True),
    sa.Column('working_tree_hash', sa.String(), nullable=True),
    sa.Column('parser_bundle_version', sa.String(), nullable=False),
    sa.Column('chunker_version', sa.String(), nullable=False),
    sa.Column('retrieval_policy_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_snapshots_repo_status', ['repository_id', 'status'], unique=False)

    op.create_table('chunk_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('logical_chunk_id', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('parser_version', sa.String(), nullable=False),
    sa.Column('chunker_version', sa.String(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('retrieval_content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['logical_chunk_id'], ['logical_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chunk_versions', schema=None) as batch_op:
        batch_op.create_index('ix_chunk_versions_logical', ['logical_chunk_id'], unique=False)

    op.create_table('files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('relative_path', sa.String(), nullable=False),
    sa.Column('normalized_path', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('generated', sa.Boolean(), nullable=False),
    sa.Column('binary', sa.Boolean(), nullable=False),
    sa.Column('parse_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'normalized_path', name='uq_files_snapshot_path')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index('ix_files_content_hash', ['content_hash'], unique=False)
        batch_op.create_index('ix_files_snapshot', ['snapshot_id'], unique=False)

    op.create_table('index_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repository_id', sa.String(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('index_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_index_jobs_status', ['status'], unique=False)

    op.create_table('snapshot_chunk_membership',
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('chunk_version_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_version_id'], ['chunk_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', 'chunk_version_id')
    )
    with op.batch_alter_table('snapshot_chunk_membership', schema=None) as batch_op:
        batch_op.create_index('ix_membership_chunk_version', ['chunk_version_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snapshot_chunk_membership', schema=None) as batch_op:
        batch_op.drop_index('ix_membership_chunk_version')

    op.drop_table('snapshot_chunk_membership')
    with op.batch_alter_table('index_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_index_jobs_status')

    op.drop_table('index_jobs')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index('ix_files_snapshot')
        batch_op.drop_index('ix_files_content_hash')

    op.drop_table('files')
    with op.batch_alter_table('chunk_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_chunk_versions_logical')

    op.drop_table('chunk_versions')
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshots_repo_status')

    op.drop_table('snapshots')
    op.drop_table('model_migrations')
    with op.batch_alter_table('logical_chunks', schema=None) as batch_op:
        batch_op.drop_index('ix_logical_chunks_repo_path')

    op.drop_table('logical_chunks')
    op.drop_table('repositories')
    with op.batch_alter_table('embedding_records', schema=None) as batch_op:
        batch_op.drop_index('ix_embedding_records_content')

    op.drop_table('embedding_records')
    # ### end Alembic commands ###
