/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/change-analysis/commits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Commits */
        post: operations["analyze_commits_v1_change_analysis_commits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/change-analysis/working-tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Working Tree */
        post: operations["analyze_working_tree_v1_change_analysis_working_tree_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/change-analysis/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis */
        get: operations["get_analysis_v1_change_analysis__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/change-analysis/{analysis_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report
         * @description Render a stored analysis. Every format reads the same persisted rows.
         */
        get: operations["get_report_v1_change_analysis__analysis_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_v1_conversations_get"];
        put?: never;
        /** Create Conversation */
        post: operations["create_conversation_v1_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/messages/{message_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Feedback */
        post: operations["submit_feedback_v1_conversations_messages__message_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/messages/{message_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Message */
        post: operations["retry_message_v1_conversations_messages__message_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation_v1_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /** Delete Conversation */
        delete: operations["delete_conversation_v1_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        /** Update Conversation */
        patch: operations["update_conversation_v1_conversations__conversation_id__patch"];
        trace?: never;
    };
    "/v1/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Messages */
        get: operations["list_messages_v1_conversations__conversation_id__messages_get"];
        put?: never;
        /**
         * Submit Message
         * @description Ask a question and return the finished turn.
         *
         *     Phase 5 answers deterministically and synchronously, so the answer is ready
         *     when this returns. P5-04 adds the streamed view of the same run; the
         *     persisted message stays the authoritative one either way.
         */
        post: operations["submit_message_v1_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{conversation_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Conversation
         * @description Stream the active run's events, resuming after the client's position.
         *
         *     Resume is accepted two ways because the browser leaves no choice:
         *     `EventSource` cannot set request headers, so it cannot send
         *     `Last-Event-ID` on the initial connection. The header is the standard and
         *     wins when both are present; `?after=` is what a browser client can
         *     actually use.
         */
        get: operations["stream_conversation_v1_conversations__conversation_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Evidence
         * @description Re-verify a stored evidence region against the file on disk.
         */
        get: operations["get_evidence_v1_evidence__evidence_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get File */
        get: operations["get_file_v1_files__file_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/message-runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Run
         * @description Ask a run to stop.
         *
         *     202, not 204: cancellation is cooperative, so this acknowledges the request
         *     rather than asserting the run has stopped. The run's own terminal event is
         *     what says that.
         */
        post: operations["cancel_run_v1_message_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_v1_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Repositories */
        get: operations["list_repositories_v1_repositories_get"];
        put?: never;
        /** Register Repository */
        post: operations["register_repository_v1_repositories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{repository_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Repository */
        get: operations["get_repository_v1_repositories__repository_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{repository_id}/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Repository Diagnostics */
        get: operations["repository_diagnostics_v1_repositories__repository_id__diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{repository_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Repository Files
         * @description List the files the active snapshot contains.
         *
         *     Paths are repository-relative, as everywhere else: the absolute root is not
         *     echoed back, so a screenshot or diagnostic bundle cannot leak it.
         */
        get: operations["repository_files_v1_repositories__repository_id__files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{repository_id}/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Index Repository */
        post: operations["index_repository_v1_repositories__repository_id__index_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{repository_id}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rollback
         * @description Restore the previous snapshot as active.
         *
         *     The escape hatch for an activation that turned out to be wrong. With no
         *     previous snapshot to return to this is a conflict, not a server error.
         */
        post: operations["rollback_v1_repositories__repository_id__rollback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{repository_id}/snapshots/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active Snapshot */
        get: operations["active_snapshot_v1_repositories__repository_id__snapshots_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{repository_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Repository Status */
        get: operations["repository_status_v1_repositories__repository_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{repository_id}/watch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Watch
         * @description Report the watch switch and what the watcher is actually doing.
         */
        get: operations["get_watch_v1_repositories__repository_id__watch_get"];
        /**
         * Set Watch
         * @description Turn continuous freshness on or off for one repository.
         *
         *     The decision is persisted, so it survives a restart: turning the watcher off
         *     is a statement about the repository, not about this process.
         */
        put: operations["set_watch_v1_repositories__repository_id__watch_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Files */
        get: operations["search_files_v1_search_files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search/symbols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Symbols */
        get: operations["search_symbols_v1_search_symbols_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Text */
        get: operations["search_text_v1_search_text_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/symbols/{symbol_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Symbol */
        get: operations["get_symbol_v1_symbols__symbol_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/symbols/{symbol}/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Symbol Relations */
        get: operations["symbol_relations_v1_symbols__symbol__relations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisSide
         * @description Which side of a change a piece of evidence belongs to.
         *
         *     Base-side evidence is hash-verified at analysis time and historical by
         *     construction; it is labeled as base so a reader never mistakes it for the
         *     current snapshot's content.
         * @enum {string}
         */
        AnalysisSide: "base" | "target";
        /**
         * AnalysisStateRef
         * @description One side of a change: the ref the caller asked for and what it resolved
         *     to.
         *
         *     The base side carries no snapshot ID — it is reconstructed in memory or read
         *     from Git objects, never a stored active snapshot. The target side carries
         *     the active snapshot ID it was analyzed against, so a reader can tell exactly
         *     which snapshot the analysis is bound to.
         */
        AnalysisStateRef: {
            /** Commit */
            commit: string | null;
            freshness: components["schemas"]["SnapshotFreshness"];
            /** Ref */
            ref: string;
            /** Snapshot Id */
            snapshot_id: string | null;
        };
        /** Answer */
        Answer: {
            /** Claims */
            claims: components["schemas"]["Claim"][];
            /** Summary */
            summary: string;
        };
        /**
         * ChangeAnalysisKind
         * @description Which form of diff an analysis compares.
         * @enum {string}
         */
        ChangeAnalysisKind: "working_tree" | "commit_range";
        /**
         * ChangeAnalysisReport
         * @description The persisted, machine-readable rendering of one change analysis.
         */
        ChangeAnalysisReport: {
            /** Analysis Id */
            analysis_id: string;
            base: components["schemas"]["AnalysisStateRef"];
            /** Changed Files */
            changed_files?: components["schemas"]["ChangedFile"][];
            /** Changed Symbols */
            changed_symbols?: components["schemas"]["ChangedSymbol"][];
            /** Completed At */
            completed_at?: string | null;
            /**
             * Contract Version
             * @default 1.0
             * @constant
             */
            contract_version: "1.0";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Evidence */
            evidence?: components["schemas"]["ChangeEvidenceItem"][];
            /** Findings */
            findings?: components["schemas"]["Finding"][];
            /** Impact Edges */
            impact_edges?: components["schemas"]["ImpactEdge"][];
            kind: components["schemas"]["ChangeAnalysisKind"];
            /** Limitations */
            limitations?: string[];
            overall_risk: components["schemas"]["OverallRisk"];
            /** Repository Id */
            repository_id: string;
            /** Request Id */
            request_id: string;
            status: components["schemas"]["ChangeAnalysisStatus"];
            target: components["schemas"]["AnalysisStateRef"];
            /** Test Gaps */
            test_gaps?: string[];
            /** Timing Ms */
            timing_ms?: {
                [key: string]: number;
            };
            /** Warnings */
            warnings?: string[];
        };
        /**
         * ChangeAnalysisStatus
         * @description Lifecycle of one change analysis.
         * @enum {string}
         */
        ChangeAnalysisStatus: "analyzing" | "completed" | "failed";
        /**
         * ChangeEvidenceItem
         * @description One piece of analysis-scoped evidence, explicitly base- or target-side.
         *
         *     Unlike :class:`Evidence`, the analysis evidence model carries a ``side``
         *     rather than a repository-wide ``snapshot_id``: the base side of a working
         *     tree has no stored snapshot, only a commit, and pretending otherwise would
         *     hide the historical nature of base-side citations.
         */
        ChangeEvidenceItem: {
            /** Confidence */
            confidence: number;
            /** Content Hash */
            content_hash: string;
            derivation: components["schemas"]["Derivation"];
            /** End Line */
            end_line: number;
            /** Evidence Id */
            evidence_id: string;
            /** File Path */
            file_path: string;
            side: components["schemas"]["AnalysisSide"];
            /** Start Line */
            start_line: number;
            /** Symbol */
            symbol?: string | null;
        };
        /**
         * ChangeKind
         * @description What happened to one symbol across a change.
         * @enum {string}
         */
        ChangeKind: "added" | "deleted" | "modified" | "moved" | "dependency";
        /**
         * ChangedFile
         * @description One file in the file-level diff.
         */
        ChangedFile: {
            /** Base Path */
            base_path?: string | null;
            change_kind: components["schemas"]["FileChangeKind"];
            /**
             * Content Hash Changed
             * @default false
             */
            content_hash_changed: boolean;
            /** Path */
            path: string;
        };
        /**
         * ChangedSymbol
         * @description One symbol that differs between the base and target states.
         *
         *     A deleted or moved-from symbol carries base line range and a base file path;
         *     an added symbol carries target range; a modified symbol carries target
         *     range and, when its content also moved, a base file path. The two are kept
         *     consistent: base lines without a base file is a contradiction the contract
         *     refuses, because a citation with no file is not a citation.
         */
        ChangedSymbol: {
            /** Base End Line */
            base_end_line?: number | null;
            /** Base File Path */
            base_file_path?: string | null;
            /** Base Start Line */
            base_start_line?: number | null;
            change_kind: components["schemas"]["ChangeKind"];
            /** Confidence */
            confidence: number;
            derivation: components["schemas"]["Derivation"];
            /** File Path */
            file_path: string;
            /** Public */
            public: boolean;
            /** Qualified Name */
            qualified_name: string;
            /** Signature Changed */
            signature_changed: boolean;
            symbol_kind: components["schemas"]["SymbolKind"];
            /** Target End Line */
            target_end_line?: number | null;
            /** Target Start Line */
            target_start_line?: number | null;
        };
        /** Claim */
        Claim: {
            /** Claim Id */
            claim_id: string;
            /** Confidence */
            confidence: number;
            derivation: components["schemas"]["Derivation"];
            /** Evidence Ids */
            evidence_ids: string[];
            /** Text */
            text: string;
        };
        /**
         * CommitRangeRequest
         * @description Analyze one commit range.
         */
        CommitRangeRequest: {
            /** Base Ref */
            base_ref: string;
            /** Repository Id */
            repository_id: string;
            /**
             * Target Ref
             * @default HEAD
             */
            target_ref: string;
        };
        /**
         * Conversation
         * @description One persisted thread, always bound to a single repository.
         *
         *     A conversation never changes repository: switching requires a new thread
         *     (Section 14.5), so a historical answer can never be reinterpreted against a
         *     repository it did not examine.
         */
        Conversation: {
            /** Archived At */
            archived_at?: string | null;
            /** Conversation Id */
            conversation_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Message At */
            last_message_at?: string | null;
            /** Repository Id */
            repository_id: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ConversationPage
         * @description One page of conversations, newest activity first.
         */
        ConversationPage: {
            /** Items */
            items?: components["schemas"]["Conversation"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** CreateConversationRequest */
        CreateConversationRequest: {
            /** Repository Id */
            repository_id: string;
            /** Title */
            title?: string | null;
        };
        /**
         * Derivation
         * @enum {string}
         */
        Derivation: "deterministic" | "static_resolved" | "high_confidence_heuristic" | "low_confidence_heuristic" | "semantic_candidate" | "model_generated" | "unsupported";
        /** DiagnosticsResponse */
        DiagnosticsResponse: {
            limits: components["schemas"]["LimitsResponse"];
            /** Parse Error Count */
            parse_error_count: number;
            /** Repository Id */
            repository_id: string;
            /** Skipped By Reason */
            skipped_by_reason: {
                [key: string]: number;
            };
            /** Snapshot Id */
            snapshot_id: string | null;
            /** Warnings */
            warnings: string[];
        };
        /** Evidence */
        Evidence: {
            /** Confidence */
            confidence: number;
            /** Content Hash */
            content_hash: string;
            derivation: components["schemas"]["Derivation"];
            /** End Line */
            end_line: number;
            /** Evidence Id */
            evidence_id: string;
            /** Excerpt */
            excerpt: string;
            /** File Path */
            file_path: string;
            /** Repository Id */
            repository_id: string;
            /** Snapshot Id */
            snapshot_id: string;
            /** Start Line */
            start_line: number;
            /** Symbol */
            symbol?: string | null;
            validation: components["schemas"]["EvidenceValidation"];
        };
        /**
         * EvidenceValidation
         * @enum {string}
         */
        EvidenceValidation: "valid" | "invalid";
        /** FeedbackRequest */
        FeedbackRequest: {
            /** Rating */
            rating: string;
            /** Reason Code */
            reason_code?: string | null;
        };
        /**
         * FileChangeKind
         * @description The file-level diff classification.
         * @enum {string}
         */
        FileChangeKind: "added" | "deleted" | "modified" | "renamed";
        /**
         * FileClassification
         * @description How a file participates in repository truth and impact analysis.
         * @enum {string}
         */
        FileClassification: "source_code" | "test_code" | "documentation" | "architecture_decision" | "api_specification" | "configuration" | "database_schema" | "migration" | "dependency_manifest" | "lockfile" | "infrastructure" | "generated" | "vendor" | "binary" | "unknown";
        /**
         * FileDetail
         * @description One file of the active snapshot, with its snapshot stated.
         */
        FileDetail: {
            file: components["schemas"]["FileRecord"];
            snapshot: components["schemas"]["SnapshotReference"];
        };
        /** FileEntry */
        FileEntry: {
            /** Classification */
            classification: string;
            /** File Id */
            file_id: string;
            /** Language */
            language: string;
            /** Line Count */
            line_count: number;
            /** Path */
            path: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /**
         * FileRecord
         * @description One file admitted into a snapshot.
         */
        FileRecord: {
            classification: components["schemas"]["FileClassification"];
            /** Content Hash */
            content_hash: string;
            /** Display Path */
            display_path: string;
            /** File Id */
            file_id: string;
            /** Language */
            language: string;
            /** Line Count */
            line_count: number;
            /** Relative Path */
            relative_path: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** FilesResponse */
        FilesResponse: {
            /** Files */
            files: components["schemas"]["FileEntry"][];
            /** Repository Id */
            repository_id: string;
            snapshot: components["schemas"]["SnapshotReference"];
        };
        /** Finding */
        Finding: {
            /** Code */
            code: string;
            /** Confidence */
            confidence: number;
            derivation: components["schemas"]["Derivation"];
            /** Description */
            description: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Limitations */
            limitations?: string[];
            /** Remediation */
            remediation?: string | null;
            severity: components["schemas"]["Severity"];
            /** Title */
            title: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImpactEdge
         * @description One edge in the impact graph, labeled but not cited.
         *
         *     An impact edge is a graph fact with a derivation and a confidence; it is
         *     not a citable region of source. Keeping evidence off the edge is what keeps
         *     the response's evidence list minimal and the exact/containing metrics
         *     meaningful, per ADR-0003 and ADR-0005.
         */
        ImpactEdge: {
            /** Confidence */
            confidence: number;
            derivation: components["schemas"]["Derivation"];
            kind: components["schemas"]["RelationKind"];
            /** Source */
            source: string;
            /** Target */
            target: string;
        };
        /** IndexResponse */
        IndexResponse: {
            /** File Count */
            file_count: number;
            /** Job Id */
            job_id: string;
            /** Parse Error Count */
            parse_error_count: number;
            /** Parsed File Count */
            parsed_file_count: number;
            /** Skipped File Count */
            skipped_file_count: number;
            /** Snapshot Id */
            snapshot_id: string;
            /** State */
            state: string;
            /** Warnings */
            warnings: string[];
        };
        /** LimitsResponse */
        LimitsResponse: {
            /** Max Depth */
            max_depth: number;
            /** Max File Bytes */
            max_file_bytes: number;
            /** Max Files */
            max_files: number;
            /** Max Relative Path Length */
            max_relative_path_length: number;
        };
        /**
         * Message
         * @description One turn in a conversation.
         *
         *     ``sequence_number`` starts at 1 and orders the thread; it is also the
         *     stream's resume key, so 0 is reserved to mean "nothing yet".
         */
        Message: {
            /** Completed At */
            completed_at?: string | null;
            /**
             * Content
             * @default
             */
            content: string;
            /** Conversation Id */
            conversation_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Code */
            error_code?: string | null;
            /** Message Id */
            message_id: string;
            role: components["schemas"]["MessageRole"];
            /** Sequence Number */
            sequence_number: number;
            status: components["schemas"]["MessageStatus"];
        };
        /**
         * MessageEvidenceItem
         * @description One citation attached to an assistant message.
         *
         *     The evidence fields are snapshotted rather than joined live: a historical
         *     message must keep telling the truth it told after its snapshot is
         *     superseded, which is the same audit rule change analyses follow.
         */
        MessageEvidenceItem: {
            /** Citation Ordinal */
            citation_ordinal: number;
            /** Claim Ids */
            claim_ids?: string[];
            /** Confidence */
            confidence: number;
            /** Content Hash */
            content_hash: string;
            derivation: components["schemas"]["Derivation"];
            /** End Line */
            end_line: number;
            /** Evidence Id */
            evidence_id: string;
            /** File Path */
            file_path: string;
            /** Snapshot Id */
            snapshot_id: string;
            /** Start Line */
            start_line: number;
            /** Symbol */
            symbol?: string | null;
        };
        /**
         * MessagePage
         * @description One page of messages, in sequence order.
         */
        MessagePage: {
            /** Items */
            items?: components["schemas"]["Message"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * MessageRole
         * @description Who produced a message.
         * @enum {string}
         */
        MessageRole: "user" | "assistant" | "system_event";
        /**
         * MessageStatus
         * @description Where a message is in its lifecycle.
         *
         *     A failed or cancelled message stays visible and retryable; the states are
         *     explicit rather than a boolean so partial and failed work can be told apart
         *     from work that never started.
         * @enum {string}
         */
        MessageStatus: "queued" | "retrieving" | "generating" | "complete" | "failed" | "cancelled";
        /**
         * MessageSubmission
         * @description The result of submitting one question.
         *
         *     Phase 5 answers deterministically and synchronously, so the submission
         *     already carries the finished answer. The IDs are returned regardless of
         *     outcome: a failed or cancelled turn is still a turn the client must be able
         *     to display and retry.
         */
        MessageSubmission: {
            /**
             * Content
             * @default
             */
            content: string;
            /**
             * Contract Version
             * @default 1.0
             * @constant
             */
            contract_version: "1.0";
            /** Conversation Id */
            conversation_id: string;
            /** Error Code */
            error_code?: string | null;
            /** Evidence */
            evidence?: components["schemas"]["MessageEvidenceItem"][];
            /** Intent */
            intent: string;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Limitations */
            limitations?: string[];
            /** Message Id */
            message_id: string;
            /** Run Id */
            run_id: string;
            /** Sequence Number */
            sequence_number: number;
            /** Snapshot Id */
            snapshot_id?: string | null;
            status: components["schemas"]["MessageStatus"];
            /** User Message Id */
            user_message_id: string;
            /** Warnings */
            warnings?: string[];
        };
        /**
         * OverallRisk
         * @description The highest severity present in an analysis, or none.
         *
         *     Extends :class:`Severity` with one ``NONE`` value so an analysis with no
         *     findings can still name its overall risk honestly rather than being absent.
         * @enum {string}
         */
        OverallRisk: "critical" | "high" | "medium" | "low" | "info" | "none";
        /**
         * QueryBody
         * @description A bounded query request.
         */
        QueryBody: {
            /**
             * Depth
             * @default 2
             */
            depth: number;
            /**
             * Max Results
             * @default 10
             */
            max_results: number;
            /**
             * Mode
             * @default exact_symbol
             */
            mode: string;
            /** Query */
            query: string;
            /** Repository Id */
            repository_id: string;
        };
        /** QueryResponse */
        QueryResponse: {
            answer: components["schemas"]["Answer"];
            /**
             * Contract Version
             * @default 1.0
             * @constant
             */
            contract_version: "1.0";
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Limitations */
            limitations?: string[];
            /** Relation Paths */
            relation_paths?: components["schemas"]["RelationPath"][];
            /** Repository Id */
            repository_id: string;
            /** Request Id */
            request_id: string;
            snapshot: components["schemas"]["SnapshotReference"];
            /** Timing Ms */
            timing_ms?: {
                [key: string]: number;
            };
            /** Warnings */
            warnings?: string[];
        };
        /** RegisterRepositoryBody */
        RegisterRepositoryBody: {
            /** Display Name */
            display_name?: string | null;
            /** Path */
            path: string;
        };
        /**
         * RelationKind
         * @enum {string}
         */
        RelationKind: "CONTAINS" | "IMPORTS" | "EXPORTS" | "CALLS" | "MAY_CALL" | "INHERITS" | "IMPLEMENTS" | "OVERRIDES" | "ROUTES_TO" | "TESTS" | "DOCUMENTS" | "READS" | "WRITES" | "QUERIES" | "CONFIGURES" | "REFERENCES" | "DEPENDS_ON";
        /** RelationPath */
        RelationPath: {
            /** Steps */
            steps: components["schemas"]["RelationStep"][];
        };
        /**
         * RelationStep
         * @description One edge of a relation path, citable on its own.
         *
         *     Every step carries its own evidence, so a path is auditable edge by edge
         *     rather than as an opaque conclusion a reader has to take on faith.
         */
        RelationStep: {
            /** Confidence */
            confidence: number;
            derivation: components["schemas"]["Derivation"];
            /** Evidence Id */
            evidence_id: string;
            kind: components["schemas"]["RelationKind"];
            /** Source */
            source: string;
            /** Target */
            target: string;
        };
        /** RepositoryResponse */
        RepositoryResponse: {
            /** Created At */
            created_at: string;
            /** Display Name */
            display_name: string;
            /** Repository Id */
            repository_id: string;
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "critical" | "high" | "medium" | "low" | "info";
        /**
         * SnapshotFreshness
         * @enum {string}
         */
        SnapshotFreshness: "fresh" | "stale" | "partial" | "unknown";
        /** SnapshotReference */
        SnapshotReference: {
            freshness: components["schemas"]["SnapshotFreshness"];
            /** Git Head */
            git_head: string | null;
            /** Semantic Coverage */
            semantic_coverage: number;
            /** Snapshot Id */
            snapshot_id: string;
            /** Working Tree Fingerprint */
            working_tree_fingerprint: string;
        };
        /** StatusResponse */
        StatusResponse: {
            /** File Count */
            file_count: number;
            /** Parse Error Count */
            parse_error_count: number;
            /** Repository Id */
            repository_id: string;
            snapshot: components["schemas"]["SnapshotReference"] | null;
            /** Symbol Count */
            symbol_count: number;
            /** Warnings */
            warnings: string[];
        };
        /** SubmitMessageRequest */
        SubmitMessageRequest: {
            /** Content */
            content: string;
        };
        /**
         * SymbolDetail
         * @description One symbol of the active snapshot, with its file path resolved.
         */
        SymbolDetail: {
            /** File Path */
            file_path: string;
            snapshot: components["schemas"]["SnapshotReference"];
            symbol: components["schemas"]["SymbolRecord"];
        };
        /**
         * SymbolKind
         * @enum {string}
         */
        SymbolKind: "MODULE" | "PACKAGE" | "CLASS" | "INTERFACE" | "ENUM" | "FUNCTION" | "METHOD" | "CONSTRUCTOR" | "PROPERTY" | "FIELD" | "CONSTANT" | "TYPE_ALIAS" | "ROUTE" | "TEST" | "FIXTURE" | "CONFIG_KEY" | "DATABASE_TABLE" | "DATABASE_COLUMN" | "SQL_QUERY" | "DOCUMENT_SECTION";
        /**
         * SymbolRecord
         * @description One symbol definition located in one file of one snapshot.
         */
        SymbolRecord: {
            /** Content Hash */
            content_hash: string;
            /** End Byte */
            end_byte: number;
            /** End Line */
            end_line: number;
            /** File Id */
            file_id: string;
            kind: components["schemas"]["SymbolKind"];
            /** Module Path */
            module_path: string;
            /** Name */
            name: string;
            /** Qualified Name */
            qualified_name: string;
            /** Signature */
            signature: string | null;
            /** Start Byte */
            start_byte: number;
            /** Start Line */
            start_line: number;
            /** Symbol Id */
            symbol_id: string;
            /** Symbol Version Id */
            symbol_version_id: string;
            /**
             * Visibility
             * @enum {string}
             */
            visibility: "public" | "private";
        };
        /**
         * UpdateConversationRequest
         * @description Rename, archive, or both. Unarchiving is not offered yet: nothing in
         *     Phase 5 needs it, and an unused write path is an untested one.
         */
        UpdateConversationRequest: {
            /** Archived */
            archived?: boolean | null;
            /** Title */
            title?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WatchResponse
         * @description Whether continuous freshness is on for a repository, and how it is doing.
         *
         *     `enabled` is the stored decision; `running` is the observed reality. They
         *     disagree when a watcher could not start — a vanished directory, exhausted
         *     handles — and showing only one of them would hide exactly that case.
         */
        WatchResponse: {
            /** Enabled */
            enabled: boolean;
            /** Failure Count */
            failure_count: number;
            /** Last Error */
            last_error: string | null;
            /** Pending */
            pending: boolean;
            /** Repository Id */
            repository_id: string;
            /** Running */
            running: boolean;
        };
        /** WatchUpdate */
        WatchUpdate: {
            /** Enabled */
            enabled: boolean;
        };
        /**
         * WorkingTreeRequest
         * @description Analyze the working tree against a base ref.
         */
        WorkingTreeRequest: {
            /**
             * Base Ref
             * @default HEAD
             */
            base_ref: string;
            /** Repository Id */
            repository_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_commits_v1_change_analysis_commits_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommitRangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeAnalysisReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_working_tree_v1_change_analysis_working_tree_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkingTreeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeAnalysisReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_v1_change_analysis__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeAnalysisReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_v1_change_analysis__analysis_id__report_get: {
        parameters: {
            query?: {
                report_format?: "json" | "markdown" | "sarif";
            };
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_v1_conversations_get: {
        parameters: {
            query: {
                repository_id: string;
                limit?: number;
                cursor?: string | null;
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation_v1_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback_v1_conversations_messages__message_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_message_v1_conversations_messages__message_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSubmission"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_v1_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_v1_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_conversation_v1_conversations__conversation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConversationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_v1_conversations__conversation_id__messages_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_message_v1_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSubmission"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_conversation_v1_conversations__conversation_id__stream_get: {
        parameters: {
            query?: {
                after?: number | null;
            };
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_v1_evidence__evidence_id__get: {
        parameters: {
            query: {
                repository_id: string;
            };
            header?: never;
            path: {
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_v1_files__file_id__get: {
        parameters: {
            query: {
                repository_id: string;
            };
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_v1_message_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_v1_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_repositories_v1_repositories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryResponse"][];
                };
            };
        };
    };
    register_repository_v1_repositories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRepositoryBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repository_v1_repositories__repository_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    repository_diagnostics_v1_repositories__repository_id__diagnostics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    repository_files_v1_repositories__repository_id__files_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_repository_v1_repositories__repository_id__index_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rollback_v1_repositories__repository_id__rollback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotReference"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    active_snapshot_v1_repositories__repository_id__snapshots_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotReference"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    repository_status_v1_repositories__repository_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_watch_v1_repositories__repository_id__watch_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_watch_v1_repositories__repository_id__watch_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_files_v1_search_files_get: {
        parameters: {
            query: {
                repository_id: string;
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_symbols_v1_search_symbols_get: {
        parameters: {
            query: {
                repository_id: string;
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_text_v1_search_text_get: {
        parameters: {
            query: {
                repository_id: string;
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_symbol_v1_symbols__symbol_id__get: {
        parameters: {
            query: {
                repository_id: string;
            };
            header?: never;
            path: {
                symbol_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymbolDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    symbol_relations_v1_symbols__symbol__relations_get: {
        parameters: {
            query: {
                repository_id: string;
                view?: "callers" | "callees" | "dependencies" | "dependents" | "exports" | "tests" | "documents" | "trace";
                depth?: number;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
